services:
  contiki-ng:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/home/user/contiki-ng/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    privileged: true
    command: sleep infinity